---
title: "final project 1"
author: "Rachael Jaffe"
date: "09/11/2021"
output: html_document
---
## Libraries and initialize
```{r}
rm(list = ls())
library(tidyverse)
library(readxl)
library(janitor)
library(lubridate) 
library(purrr)
library(stringr)

dir <- setwd(getwd())

```


## Read in data
```{r death(outcome)}
deathtable_expansion <- read_xlsx("deathtable_expansion.xlsx")
deathtable_expansion <- deathtable_expansion %>% mutate(Population = as.numeric(Population))

combined_death <- deathtable_expansion %>% group_by(State, Year) %>% mutate(all_deaths = sum(Deaths), all_pop = sum(Population, na.rm=TRUE), rate = all_deaths/all_pop) %>% distinct(State, Year, .keep_all = TRUE) %>% select(State, Year, all_deaths, all_pop, rate)
```

```{r eduation}
# education <- read_xls("Education_state.xls") 
# education <- education[-c(1,2,3),]
# education <- education %>% row_to_names(row_number = 1)
# education <- education %>% select(State, `Percent of adults with less than a high school diploma, 2015-19`:`Percent of adults with a bachelor's degree or higher, 2015-19`)
```

```{r unemployment}
unemployment <- read_xlsx("Unemployment (1).xlsx")
unemployment<- unemployment[-c(1,2,3),]
unemployment<- unemployment %>% row_to_names(row_number = 1)
unemployment <- unemployment %>% select(State, Area_name, Civilian_labor_force_2010:Med_HH_Income_Percent_of_State_Total_2019)
unemployment <- unemployment %>% filter(!grepl(",", Area_name)) ## remove counties
unemployment <- unemployment[-10,] ##remove DC (its duplicated)
unemployment1 <- unemployment %>% pivot_longer(cols = c(Civilian_labor_force_2010:Med_HH_Income_Percent_of_State_Total_2019), names_to = "unemploy_variable") 
unemployment1 <- unemployment1 %>% mutate(Year = str_extract(unemploy_variable, "[^_]+$")) %>% mutate(Year = as.numeric(Year)) ## get year from each variable
unemployment1 <- unemployment1 %>% mutate(unemploy_variable = gsub('.{5}$', '', unemploy_variable)) ## remove year from variable name
unemployment1 <-unemployment1 %>% filter(!State == "US")
unemployment1 <- unemployment1 %>% rename(State = Area_name, state_abrev = State)
unemployment2 <- unemployment1 %>% pivot_wider(id_cols = c(State:Year), names_from = unemploy_variable, values_from = value)
unemployment2 <- unemployment2 %>% mutate(State = as.factor(State)) %>%mutate_if(is.character,as.numeric)

```
```{r workforce}
workforce <- read_excel("physician_total (1).xlsx", sheet = "Sheet4")
workforce <- workforce %>% select(STATE:EMP_2019)
workforce <- workforce %>% rename(State = STATE)
workforce <- workforce %>% pivot_longer(cols = c(EMP_2010:EMP_2019), names_to = "physician_variable")
workforce  <- workforce  %>% mutate(Year = str_extract(physician_variable, "[^_]+$")) %>% mutate(Year = as.numeric(Year))
workforce<- workforce %>% mutate(physician_variable = gsub('.{5}$', '', physician_variable)) ## remove year from variable name
workforce <- workforce %>% pivot_wider(names_from = physician_variable, values_from = value)
workforce <- workforce %>% rename(physician_total = EMP)
```

```{r injection}
injection <- read_excel("injection.xlsx",sheet = "Sheet2")
injection <- injection %>% select(STATE:LEGAL_2019)
injection <- injection %>% rename(State = STATE)
injection <- injection %>% pivot_longer(cols = c(LEGAL_2010:LEGAL_2019), names_to = "variable")
injection  <- injection  %>% mutate(Year = str_extract(variable, "[^_]+$")) %>% mutate(Year = as.numeric(Year))
injection<- injection %>% mutate(variable = gsub('.{5}$', '', variable)) ## remove year from variable name
injection <- injection %>% pivot_wider(names_from = variable, values_from = value)
injection <- injection %>% rename(legal_injection = LEGAL)
```


```{r expansion date}
expansion_date <- read_excel("ExpansionData.xlsx")
expansion_date <- expansion_date %>% rename(date = `Expansion date`)
expansion_date[ expansion_date == "NA" ] <- NA
expansion_date <- expansion_date %>% mutate(date = as.numeric(date))
expansion_date <- expansion_date %>% mutate_at(vars(date), ~as.Date(., origin = "1899-12-30"))

```

```{r age}
age_data_0 <- read.csv("Age data.csv")
age_data1 <- age_data_0[-c(1:4)]
age_data1 <- age_data1[-c(4)]
colnames(age_data1) <- c("name", "sex", "age", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
age_data1 <- age_data1[!(age_data1$age ==999),] 
age_data1["age"][age_data1["age"] == 0] <- 1.00000000000001 ## changes age 0 to 1 so that we can get the total people

age_data1 <- age_data1 %>% mutate(across(contains('20'),  ## does age * # people per year so we can do the median
                                         .fns = list(f = ~(.*age)), 
                                         .names = "{col}_{fn}")) 
                                  
age_data2 <- age_data1 %>% filter(name != "United States") 

age_data3 <- age_data2 %>% group_by(name) %>% mutate(across(contains('20'), 
                                                            .fns = list(s = ~(sum(.))), 
                                                            .names = "{col}_{fn}")) 
age_data4 <- age_data3 %>% distinct(name, .keep_all=TRUE) %>% select(-c(sex, age)) %>% select(name, c(`2010_s`:`2019_f_s`))

patterns <- unique(substr(names(age_data4), 1, 4))  # store patterns in a vector
patterns <- patterns[-1]
new <- data.frame(sapply(patterns, function(x) age_data4[,grep(x, names(age_data4))][2] / age_data4[,grep(x, names(age_data4))][1]))  # loop through
final <- new %>% cbind(age_data4$name)
colnames(final) <- c("2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "State")
final <- final %>% select(State, c(`2010`:`2019`))
final <- final %>% pivot_longer(cols = c(`2010`:`2019`), names_to = "Year")
final <- final %>% rename("Mean_Age" = value)
final <- final %>% mutate(Year = as.numeric(Year))
```


```{r medicaid spending}
spending <- read_xlsx("Annual_bydrug_2019Q3.xlsx", sheet = "Annual_bydrug_2019Q3")
state_names <- read_xlsx("Annual_bydrug_2019Q3.xlsx", sheet = "Sheet1")
spending <- spending %>% full_join(state_names)

spending <- spending %>% filter(drugtype == "all") %>% rename(Year = year) %>% select(State, Year, imprx:percap_unadjmedamt)
```


```{r other death}
other_deaths <- read_xlsx("Underlying Cause of Death, 1999-2019.xlsx", sheet = "All Cause of Death")
other_deaths <- other_deaths %>% pivot_longer(cols = c(Deaths2010:Deaths2019), names_to = "variable")
other_deaths  <-other_deaths  %>% mutate(Year = str_extract(variable, "[^s]+$")) %>% mutate(Year = as.numeric(Year))
other_deaths <- other_deaths  %>% mutate(variable = gsub('.{4}$', '', variable)) ## remove year from variable name
other_deaths <- other_deaths  %>% pivot_wider(names_from = variable, values_from = value)
other_deaths  <- other_deaths  %>% rename(other_deaths = Deaths)
other_deaths <- other_deaths  %>% mutate(Year = as.numeric(Year))
```


## Concat data
```{r concat data}

##unemployment
final_data <- combined_death %>% left_join(unemployment2, by.x = c(State, Year), by.y=c(State, Year))
## expansion date
final_data <- final_data %>% full_join(expansion_date, by="State")
final_data <- final_data %>% mutate(Year = year(as.Date(as.character(Year), format = "%Y")))

## Add physician data

final_data <- final_data %>% full_join(workforce)
# final_data <- final_data %>% mutate(physician_per_pop = physician_total/all_pop)

#Add SEP data
final_data <- final_data %>% full_join(injection)

## add age data
final_data <- final_data %>% left_join(final, by = c("State", "Year"))

## spending data
final_data <- final_data %>% left_join(spending, by= c("State", "Year") )

## other deaths
final_data <- final_data %>% left_join(other_deaths, by= c("State", "Year") )
# final_data <- final_data %>% mutate(other_deaths_perpop = other_deaths/all_pop)

final_data <- final_data %>% select(-c(Median_Household_Income, Med_HH_Income_Percent_of_State_Total))
```

```{r groupdata}
## group data based on expansion date
# final_data <- final_data %>% mutate(expan_group = case_when(
#   is.na(date) == TRUE ~ "no_expansion",
#   date < as.Date("2014-02-01") ~ "early_expansion",
#   date > as.Date("2014-02-01") & date < as.Date("2018-01-01") ~"middle_expansion",
#   date > as.Date("2018-01-01") ~ "late_expansion"
# ))
final_data <- final_data %>% mutate(expan_group = case_when(
  is.na(date) == TRUE ~ "no_expansion",
  date < as.Date("2018-01-01") ~ "expansion",
  date > as.Date("2018-01-01") ~ "no_expansion"
))
final_data <- final_data %>% filter(!State %in% c("California", "Connecticut", "District of Columbia", "Minnestoa", "Washington"))
final_data <- final_data %>% mutate(expan_group = as.factor(expan_group))
final_data <- final_data %>% filter(!is.na(Year))
```

## group by expansion date
```{r}
final_data_grouped <- final_data %>% group_by(expan_group, Year) %>% select_if(is.numeric) %>% summarise_at(vars(-group_cols(), c(all_deaths, all_pop, Employed, Unemployed, Civilian_labor_force)), sum, na.rm=TRUE)
final_data_grouped <- final_data_grouped %>% mutate(Unemployment_rate  = Unemployed / Civilian_labor_force,
                                                    rate = all_deaths / all_pop) %>% rename(death_rate= rate)
                                          

```


## Let's look at plots
```{r initial plots}
final_data_grouped %>% ggplot(aes(Year, death_rate, color=expan_group))+stat_summary(geom = 'line') +
    #geom_vline(xintercept = 1994) +
  scale_x_continuous(breaks =seq(2010, 2019,1))+
    theme_minimal()
ggsave("initial_plot.png")
```

## organize data for d-d 
```{r}
# dummy for time
final_data_grouped <- final_data_grouped %>% mutate(time = ifelse(Year >= 2016, 1, 0 ))
final_data_grouped <- final_data_grouped %>% mutate(treated = ifelse(!expan_group %in% c("no_expansion", "late_expansion"), 1, 0 ))
final_data_grouped <- final_data_grouped %>% mutate(did = time*treated)


```

## modeling
```{r}
didreg1 = lm(death_rate ~ Unemployment_rate + treated*time, data = final_data_grouped)
summary(didreg1)
```

